<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DeviceLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceLogRepository extends EntityRepository
{
    public function findByDay(\DateTime $day)
    {
        $query = $this->getEntityManager()->createQuery(
            'select dl, d from \App\Entity\DeviceLog dl join dl.device d where dl.date between :datestart and :dateend order by d.id asc, dl.date asc'
        );
        $query->setParameters(
            array(
                'datestart' => $day->format('Y-m-d'),
                'dateend' => $day->add(new \DateInterval('P1D'))->format('Y-m-d'),
            )
        );
        return $query->getResult();
    }
}
