<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TimeBlocksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeBlocksRepository extends EntityRepository
{
    // @todo: Fetch last timeblock
    // if older then yesterday, return true?
}
