language: php
php:
    - 5.4
    - 5.5
    - 5.6

before_install:
- composer install --dev
- cp config/app/config.yml-dist config/app/config.yml

after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover

script:
- vendor/bin/phpunit -c tests/phpunit.xml --coverage-text --coverage-clover=coverage.clover
