FROM php:5.6-cli
MAINTAINER Tim de Pater

# Install Node.js and other dependencies
RUN apt-get update && \
    apt-get install -y nmap libsqlite3-dev && \
    docker-php-ext-install pdo_sqlite

# Provides cached layer for composer packages

# Define working directory
WORKDIR /src
ADD . /src
